# Generated by Django 4.2.4 on 2024-10-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
            ],
        ),
    ]
